version: "3.8"
services:
  scraper:
    build: ./scraper
    container_name: scraper
    ports:
      - "12345:12345"   # REST
      - "50051:50051"   # gRPC
    networks:
      - app-net

  auth:
    build: ./auth
    container_name: auth
    ports:
      - "12346:12346"
    depends_on:
      - scraper
    environment:
      SCRAPER_GRPC_HOST: scraper
      SCRAPER_GRPC_PORT: 50051
    networks:
      - app-net

networks:
  app-net: