spring.application.name=scraper
server.port=12345
scraper.temprest.baseurl=https://plan-219ec-default-rtdb.europe-west1.firebasedatabase.app/
scraper.temprest.eventurl=wydarzenia.json
scraper.temprest.complexurl=https://plan-219ec-default-rtdb.europe-west1.firebasedatabase.app/wydarzenia.json
